version: '2'
services:
  web:
    build:
      context: .
    environment:
      - SERVICE_BASE_URL=http://fake-service:9090/service
      - ENV_NAME=local
      - LOG_LEVEL=debug
      - HTTP_CLIENT_MAX_IDLE_CONNS_PER_HOST=1
      - HTTP_CLIENT_MAX_IDLE_CONNS=1
      - HTTP_CLIENT_DIALER_TIMEOUT_MS=30000
      - HTTP_CLIENT_DIALER_KEEPALIVE_MS=30000
      - HTTP_CLIENT_IDLE_CONN_TIMEOUT_MS=90000
      - HTTP_CLIENT_TLS_HANDSHAKE_TIMEOUT_MS=10000
      - HTTP_CLIENT_EXPECT_CONTINUE_TIMEOUT_MS=1000
      - HTTP_CLIENT_TIMEOUT_MS=1500

    links:
      - fake-service
    ports:
      - "8000:8000"

  fake-service:
    image: quii/mockingjay-server:1.10.4
    volumes:
      - ./fakes:/fakes
    command: -config=/fakes/fake-service.yml
    ports:
     - "9090:9090"